//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickFrame.Repository.General {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TokenStore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenStore() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickFrame.Repository.General.TokenStore", typeof(TokenStore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 insert into t_tokenstore (TokenID, TokenKey, CreateTime, ExpireTime) values (@TokenID, @TokenKey, @CreateTime, @ExpireTime) 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select count(1) from t_tokenstore 的本地化字符串。
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from t_tokenstore where TokenID = @TokenID 的本地化字符串。
        /// </summary>
        internal static string DeleteByID {
            get {
                return ResourceManager.GetString("DeleteByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from t_tokenstore where TokenKey = @TokenKey 的本地化字符串。
        /// </summary>
        internal static string DeleteByKey {
            get {
                return ResourceManager.GetString("DeleteByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from t_tokenstore 的本地化字符串。
        /// </summary>
        internal static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from t_tokenstore where ClientType = @ClientType and UserID = @UserID order by LastTime desc 的本地化字符串。
        /// </summary>
        internal static string GetByClientTypeAndUserID {
            get {
                return ResourceManager.GetString("GetByClientTypeAndUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from t_tokenstore where TokenID = @TokenID 的本地化字符串。
        /// </summary>
        internal static string GetByID {
            get {
                return ResourceManager.GetString("GetByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update t_tokenstore set
        ///					OpenTime = @OpenTime,
        ///					LastTime = @LastTime,
        ///					ClientType = @ClientType,
        ///					ClientVersion = @ClientVersion,
        ///					WANIP = @WANIP,
        ///					LANIP = @LANIP,
        ///					GatewayIP = @GatewayIP,
        ///					Status = @Status,
        ///					UserID = @UserID,
        ///					UserName = @UserName,
        ///					OrganizationID = @OrganizationID,
        ///					OrganizationName = @OrganizationName,
        ///					Info = @Info
        ///				where TokenID = @TokenID 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update t_tokenstore set
        ///					LastTime = @LastTime
        ///				where TokenID = @TokenID 的本地化字符串。
        /// </summary>
        internal static string UpdateLastTime {
            get {
                return ResourceManager.GetString("UpdateLastTime", resourceCulture);
            }
        }
    }
}
